"""Per-CLI install-doc validation (Task 15.5).

Each ``install/<cli>.md`` is generated by ``crossmem docs install``
from the connector code. The renderer is exercised by the snapshot
tests under ``tests/docs/``; this test suite focuses on the
committed files in ``install/`` and asserts two contracts that the
LLM caller relies on:

1. **Header schema** — every per-CLI file satisfies the shared
   :func:`assert_install_doc_schema` contract (YAML frontmatter
   with the documented keys, five required H2 headings in order).
2. **Configure-MCP snippet parses** — the first fenced code block
   inside the ``## Configure MCP`` section is a valid JSON or YAML
   document (based on the fence language tag). This is the snippet
   the LLM is told to merge into the host config, so a parse error
   here would mean the docs ship broken instructions.

Discovery is glob-based so adding a new connector (and a new
``install/<name>.md``) automatically extends the matrix.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest
import yaml

from tests.install._helpers import assert_install_doc_schema

REPO_ROOT = Path(__file__).resolve().parents[2]
INSTALL_DIR = REPO_ROOT / "install"

# Files in ``install/`` that are not per-CLI guides. ``_template.md``
# is the schema sample (Task 15.3) and ``README.md`` documents the
# directory; both are excluded from the per-CLI matrix.
_NON_CLI_FILES: frozenset[str] = frozenset({"_template.md", "README.md"})


def _discover_install_docs() -> list[Path]:
    """Return the sorted list of ``install/<cli>.md`` files."""
    return sorted(p for p in INSTALL_DIR.glob("*.md") if p.name not in _NON_CLI_FILES)


_INSTALL_DOCS: list[Path] = _discover_install_docs()
_INSTALL_DOC_IDS: list[str] = [p.stem for p in _INSTALL_DOCS]


# Locate the fenced code block that immediately follows the
# ``## Configure MCP`` heading. The lazy ``.*?`` keeps the match to
# the **first** fence in the section even if Troubleshooting later
# introduces its own.
_CONFIGURE_MCP_FENCE_RE = re.compile(
    r"^## Configure MCP\b.*?^```(?P<lang>\w+)\r?\n(?P<body>.*?)^```",
    re.DOTALL | re.MULTILINE,
)


def _extract_configure_snippet(text: str) -> tuple[str, str]:
    """Return ``(lang, body)`` for the Configure-MCP code block."""
    match = _CONFIGURE_MCP_FENCE_RE.search(text)
    if match is None:
        msg = "no fenced code block found in '## Configure MCP' section"
        raise AssertionError(msg)
    return match.group("lang"), match.group("body")


def test_install_dir_has_per_cli_files() -> None:
    """All 12 connectors must have an ``install/<cli>.md`` committed."""
    # Hard-coded to 12 so a missing or extra file fails loudly here
    # rather than as a parameterised test that silently shrinks.
    assert len(_INSTALL_DOCS) == 12, (
        f"expected 12 per-CLI install docs under {INSTALL_DIR}, "
        f"found {len(_INSTALL_DOCS)}: {[p.name for p in _INSTALL_DOCS]}"
    )


@pytest.mark.parametrize("doc_path", _INSTALL_DOCS, ids=_INSTALL_DOC_IDS)
def test_install_doc_schema(doc_path: Path) -> None:
    """Every per-CLI install doc satisfies the shared header schema."""
    assert_install_doc_schema(doc_path)


@pytest.mark.parametrize("doc_path", _INSTALL_DOCS, ids=_INSTALL_DOC_IDS)
def test_configure_mcp_snippet_parses(doc_path: Path) -> None:
    """The Configure-MCP snippet round-trips through the documented parser."""
    text = doc_path.read_text(encoding="utf-8")
    lang, body = _extract_configure_snippet(text)

    if lang == "json":
        parsed = json.loads(body)
    elif lang == "yaml":
        parsed = yaml.safe_load(body)
    else:
        msg = f"{doc_path.name}: unsupported fence language {lang!r}"
        raise AssertionError(msg)

    # The snippet wraps a per-CLI key path leading to a ``crossmem``
    # entry. We do not pin the exact key layout here (that is the
    # snapshot test's job in ``tests/docs/test_render.py``) but we
    # do assert the structural shape: a non-empty mapping containing
    # ``crossmem`` somewhere in the nested tree.
    assert isinstance(parsed, dict) and parsed, (
        f"{doc_path.name}: Configure-MCP snippet must parse to a non-empty mapping"
    )

    def _contains_crossmem_key(value: object) -> bool:
        if isinstance(value, dict):
            return "crossmem" in value or any(
                _contains_crossmem_key(v) for v in value.values()
            )
        return False

    assert _contains_crossmem_key(parsed), (
        f"{doc_path.name}: Configure-MCP snippet must define a 'crossmem' entry"
    )
